/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package org.philips.swcoe.qualityGatesDemo;

public class DemoQualityGates {
    private String name;
    public DemoQualityGates(String name) {
        this.name = name;
    }

    public String getName() {
        return this.name;
    }
}